version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - ccamel
      - fredericvilcot
      - ErikssonJoakim
      - lolottetheclash
      - AnjaMis
    assignees:
      - ccamel
      - fredericvilcot
      - lolottetheclash
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - ccamel
      - fredericvilcot
      - ErikssonJoakim
      - lolottetheclash
      - AnjaMis
    assignees:
      - ccamel
      - fredericvilcot
      - lolottetheclash
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    reviewers:
      - ccamel
      - fredericvilcot
      - ErikssonJoakim
      - lolottetheclash
      - AnjaMis
    assignees:
      - ccamel
      - fredericvilcot
      - lolottetheclash
    open-pull-requests-limit: 5
