name: Test

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-ts:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.27.0

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.19
          cache: 'pnpm'

      - name: Fetch dependencies
        run: |
          pnpm install
      - name: Test typescript
        run: |
          pnpm test
